### ISSUE TITLE
Newbie here: get SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by OlegShklyarov** [zerodytrash/TikTok-Livestream-Chat-Connector#4]
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)

I have copy pasted the example and started an app.js

**Comment by zerodytrash** [comment]
hi,

Looks like your Node.js version can't read the code.
Try to install the latest Node.js version (v16.14.0 LTS).

You can check your version with `node -v`

**Comment by zerodytrash** [comment]
You can instantiate multiple `WebcastPushConnection` objects and wrap them into a function. This allows to listen to multiple live stream chats at the same time. At the moment, I haven't noticed any IP blocking or rate limiting on the part of TikTok. I have only tested it to a maximum of 10 connections.

**Comment by OlegShklyarov** [comment]
We will try, thanks!
